macos_task:
  homebrew_cache:
    folder: /Users/admin/Library/Caches/Homebrew
  qt_cache:
    folder: /tmp/Qt
  ccache_cache:
    folder: /tmp/ccache_dir
  matrix:
    - name: Cirrus macOS
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
      mac_script:
        - mkdir artifacts
        - chmod +x "build-mac-arm64.sh"
        - ./build-mac-arm64.sh
